ci: use `ubuntu-22.04` on `sdist` for now
Should fix the issue spotted in
https://github.com/fpgmaas/deptry/actions/runs/10292527780/job/28487127720
for now:
```
  error: externally-managed-environment

  × This environment is externally managed
  ╰─> To install Python packages system-wide, try apt install
      python3-xyz, where xyz is the package you are trying to
      install.
```

Need to see how to best handle this, but in the meantime, let's revert
to a working workflow.